import {
    LuApple,
    LuBaby,
    LuBanana,
    LuBeer,
    LuBeef,
    LuCandy,
    LuCarrot,
    LuCat,
    LuCoffee,
    LuCookie,
    LuCpu,
    LuCroissant,
    LuCupSoda,
    LuDog,
    LuDrumstick,
    LuEgg,
    LuEggFried,
    LuFish,
    LuGift,
    LuGlobe,
    LuHam,
    LuHeartPulse,
    LuIceCreamCone,
    LuLeafyGreen,
    LuMicrowave,
    LuMilk,
    LuNut,
    LuPill,
    LuPizza,
    LuPopcorn,
    LuRefrigerator,
    LuSandwich,
    LuScroll,
    LuShoppingBasket,
    LuShoppingCart,
    LuShirt,
    LuSnowflake,
    LuSoup,
    LuSparkles,
    LuSprayCan,
    LuSprout,
    LuStore,
    LuTrendingUp,
    LuWine,
    LuWheat,
} from 'react-icons/lu';

/**
 * Canonical Appwrite `categories.icon` string values.
 * Lucide (react-icons/lu) for a cohesive, grocery-rich set.
 * Keep admin `categoryIconMap.jsx` in sync.
 */
export const CATEGORY_ICON_ELEMENTS = {
    'fruits-veg': <LuLeafyGreen />,
    organic: <LuSprout />,
    produce: <LuCarrot />,
    fresh: <LuApple />,
    'herbs-spices': <LuWheat />,
    dairy: <LuMilk />,
    eggs: <LuEgg />,
    meat: <LuBeef />,
    poultry: <LuDrumstick />,
    ham: <LuHam />,
    seafood: <LuFish />,
    deli: <LuSandwich />,
    bakery: <LuCroissant />,
    breakfast: <LuEggFried />,
    frozen: <LuSnowflake />,
    'ice-cream': <LuIceCreamCone />,
    beverages: <LuCupSoda />,
    coffee: <LuCoffee />,
    alcohol: <LuWine />,
    beer: <LuBeer />,
    snacks: <LuCookie />,
    candy: <LuCandy />,
    nuts: <LuNut />,
    pizza: <LuPizza />,
    popcorn: <LuPopcorn />,
    pantry: <LuShoppingBasket />,
    canned: <LuSoup />,
    international: <LuGlobe />,
    household: <LuSparkles />,
    cleaning: <LuSprayCan />,
    'paper-goods': <LuScroll />,
    health: <LuHeartPulse />,
    pharmacy: <LuPill />,
    baby: <LuBaby />,
    pets: <LuDog />,
    'pet-care': <LuCat />,
    electronics: <LuCpu />,
    fashion: <LuShirt />,
    trending: <LuTrendingUp />,
    groceries: <LuShoppingCart />,
    'ready-meals': <LuMicrowave />,
    deals: <LuGift />,
    fruit: <LuBanana />,
    chilled: <LuRefrigerator />,
    default: <LuStore />,
};

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICON_ELEMENTS).filter((k) => k !== 'default');
